name: Prairie Cardiac Foundation
favicon: null
layout_spectrum: 0.9537
typography_spectrum: 0.32469
title: Prairie Cardiac Foudation
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#020202'
    - '#e13e2c'
    - '#515151'
    - '#bfbfbf'
  brandStrength: 0.1875
  lightness: 0.5772179292980582
  saturation: 0.5885916964616627
  rhythmicContrast: 0.23340635909698904
purpose: []
